# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

DISABLE:
  - COPYPASTE
  - SPELL
  - REPOSITORY

SHOW_ELAPSED_TIME: true
IGNORE_GENERATED_FILES: true
PRINT_ALL_FILES: false
FORMATTERS_DISABLE_ERRORS: false
VALIDATE_ALL_CODEBASE: true
PRE_COMMANDS:
  - command: |
      npm install next \
                  prettier-plugin-tailwindcss \
                  eslint-config-next \
                  eslint-config-prettier \
                  eslint-plugin-prettier \
                  eslint @typescript-eslint/parser
