# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

DISABLE:
  - COPYPASTE
  - SPELL

# DISABLE_LINTERS:
#   - CSS_STYLELINT
#   - JAVASCRIPT_ES
#   - MAKEFILE_CHECKMAKE
#   - MARKDOWN_MARKDOWNLINT
#   - REPOSITORY_CHECKOV
#   - REPOSITORY_TRIVY
#   - REPOSITORY_GIT_DIFF
#   - TSX_ESLINT
#   - TYPESCRIPT_ES
#   - EDITORCONFIG_EDITORCONFIG_CHECKER

SHOW_ELAPSED_TIME: true
IGNORE_GENERATED_FILES: true
PRINT_ALL_FILES: false
FORMATTERS_DISABLE_ERRORS: false
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
JAVASCRIPT_DEFAULT_STYLE: prettier
PRE_COMMANDS:
  - command: |
      npm install eslint-plugin-react \
                  prettier-plugin-tailwindcss \
                  eslint-config-next \
                  eslint-config-prettier \
                  eslint-plugin-tailwindcss \
                  @tailwindcss/typography
